#!/usr/local/bin/perl -w
###########################################
# custom filler simulator
###########################################
use strict;
use Term::ReadKey;

$|=1;
print "$0\n";

my $user = scalar getpwuid $>;
print "type here:";

ReadMode 2;
my $pw1 = <STDIN>;
ReadMode 1;

print "\nNice.\n";
